language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script: 
  - cp etc/timelineage_config.py.dist etc/timelineage_config.py
  - pytest --cov=timelineage

after_success:
  - coveralls

  